version: '3'
services:
  uttag:
    container_name: demouttag
    image: demouttag
    build: ./demouttag
    expose: 
     - 8080
    ports:
     - 8080:8080

  db:
    container_name: database
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
     - 3306
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: uttag
      MYSQL_DATABASE: uttag
      MYSQL_USER: uttag
      MYSQL_PASSWORD: uttag

  pl-h2:
    container_name: demoplh2
    image: demopl 
    build: ./demopl
    expose:
      - 8081
    ports:
     - 8081:8081
    depends_on:
     - uttag

  pl-mysql:
    container_name: demoplmysql
    image: demopl-mysql
    build: ./jdbcdemo
    expose:
     - 8083
    ports:
     - 8083:8083
    depends_on:
     - db
     - uttag   

  client:
   container_name: democlient
   image: democlient
   build: ./democlient
   expose:
    - 8082
   ports:
    - 8082:8082
   depends_on:
    - pl-h2

      
    







