version: '3'
services:
  uttag:
    container_name: demouttag
    image: demouttag
    build: ./demouttag
    expose: 
     - 8080
    ports:
     - 8080:8080

  pl:
    container_name: demopl
    image: demopl 
    build: ./demopl
    expose:
      - 8081
    ports:
     - 8081:8081
    depends_on:
     - uttag

  client:
   container_name: democlient
   image: democlient
   build: ./democlient
   expose:
    - 8082
   ports:
    - 8082:8082
   depends_on:
    - pl







